### ISSUE TITLE
Pagination not provided className

### ISSUE THREAD

**Issue by HawkeyePierce89** [lo-tp/material-ui-pagination#10]
Hello. I can not set className for Pagination and, as a result, I can not add my styles for Pagination

```
<Pagination
  total={this.props.pages}
  current={this.props.perPage}
  display={9}
  onChange={this.onChangeHandler}
  className={cx('pagination')}
/>
```

**Comment by HawkeyePierce89** [comment]
By the way, it would be good to set individual classes for the root element, FirstPageLink, LastPageLink and intermediate buttons. For example

```
<Pagination
  total={this.props.pages}
  current={this.props.perPage}
  display={9}
  onChange={this.onChangeHandler}
  className={cx('pagination')}
  classNameFirstLink={cx('first')}
  classNameLastLink={cx('last')}
  classNameButton={cx('intermediate')}
/>
```

**Comment by lo-tp** [comment]
Thanks for your suggestion @HawkeyePierce89 .
I will try to make it possible to modify the style of the `Pagination` component.

**Comment by lo-tp** [comment]
@HawkeyePierce89 
Sorry for the delay,
With all the styles set inline by the *material-ui* lib, one has no choice but to use the `important` keyword to override the default styles.
However, we all know that we should avoid the usage of this keyword as much as possible.
So I guess the `className` prop is not the solution you are looking for.

**Comment by HawkeyePierce89** [comment]
@lo-tp 
No problems with the delay, no hurry. For override styles I have 2 choices:
1) _!important_
2) Use attribute _style_ and generate CSS in my component-file. If I using CSS Modules in project I get "chaos": all project uses CSS Modules, but in one component I need used inline styles. It's not good, I think what !important is lesser evil.

But. Material UI recommends «Overriding with Inline Styles» as first way http://www.material-ui.com/#/customization/styles Hmmm... The thought in my head: what if I imported _style.css_ as variable and set this variable for attribute _style_? 
```
import style from './style.css';
...
<SomeComponent style={style} />
```
It's working? I need time for checking this.

Can you don't close this issue until we come to a consensus?

**Comment by lo-tp** [comment]
Hi @HawkeyePierce89 
Any progress on this problem?

**Comment by HawkeyePierce89** [comment]
Sorry, I get new work on this week and I was a little busy.

**form.css**
```
form {
  background-color: forestgreen;
}
```
**somecomponent.js**
```
import formStyle from './form.css';
...
<form />
```

Form is painted in a soft green color. But it's work on all form in component :( And this idea not working.

But. May be used styles?

```
<Pagination
  total={this.props.pages}
  current={this.props.perPage}
  display={9}
  onChange={this.onChangeHandler}
  styleRoot={styleRoot}
  styleFirstLink={styleFirstLink}
  styleLastLink={styleLastLink}
  styleButton={styleButton}
/>
```

But I don't know how correctle in this case to set styles in variables.

First option: writing styles inside the component file.
Second option: writing styles as object in external file and import it.

Although this is a secondary problem.

**Comment by lo-tp** [comment]
I am with the first option.
It's not an easy job to customize the style of a `material-ui component`.
Maybe we should stick with the original design....LOL

**Comment by HawkeyePierce89** [comment]
@lo-tp

What do you think about my commit? Can I create PR?

If we have a styles, we rendering a div element with styles, otherwise we rendering you default elements from Material UI. Or is it needless? Or is it better to specify which item we want to take from Material UI?

1) **package,json** this changes need, because on Windows I can error on run npm commands
2) **README** my English is bad and I can make errors in the text.

**Comment by HawkeyePierce89** [comment]
No, it's not. I think I know how to make, A little later I'll make another commit

**Comment by lo-tp** [comment]
HI @HawkeePiece89
Thanks for your commit.
Maybe it could be greater with a demo.
We don't have to write a new page. 
A simple demo below the original one serving as a demonstration of how to use the customization mechanism you implemented is wholly enough.

**Comment by HawkeyePierce89** [comment]
@lo-tp 
Done!

**Comment by lo-tp** [comment]
@HawkeyePierce89 
Bravo
Few more things before we can move on,
We have to Increase the version number in `package.json` so we can update the npm repo and refine the README document.
Just send me a PR and I will take care of the rest thing.

**Comment by HawkeyePierce89** [comment]
+1

**Comment by lo-tp** [comment]
@HawkeyePierce89 
README refined, npm package republished. Now we are good to go.
