### ISSUE TITLE
Fails to install with webpack error

### ISSUE THREAD

**Issue by esprehn** [lo-tp/material-ui-pagination#13]
```
lerna ERR! execute npm ERR! Darwin 16.7.0
lerna ERR! execute npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
lerna ERR! execute npm ERR! node v6.10.3
lerna ERR! execute npm ERR! npm  v3.10.10
lerna ERR! execute npm ERR! path /app/node_modules/material-ui-pagination/node_modules/webpack/bin/webpack.js
lerna ERR! execute npm ERR! code ENOENT
lerna ERR! execute npm ERR! errno -2
lerna ERR! execute npm ERR! syscall chmod
lerna ERR! execute 
lerna ERR! execute npm ERR! enoent ENOENT: no such file or directory, chmod '/app/node_modules/material-ui-pagination/node_modules/webpack/bin/webpack.js'
lerna ERR! execute npm ERR! enoent ENOENT: no such file or directory, chmod '/app/node_modules/material-ui-pagination/node_modules/webpack/bin/webpack.js'
lerna ERR! execute npm ERR! enoent This is most likely not a problem with npm itself
lerna ERR! execute npm ERR! enoent and is related to npm not being able to find a file.
lerna ERR! execute npm ERR! enoent 
```

**Comment by lo-tp** [comment]
@esprehn 
Unable to reproduce this error on my MAC

**Comment by esprehn** [comment]
This reproduces on my mac with the following package.json doing `npm install` in that directory:

**package.json**
```json
{
  "name": "test",
  "description": "",
  "version": "1.0.0",
  "author": "",
  "private": true,
  "dependencies": {
    "material-ui-pagination": "^1.0.3"
  }
}
```

```
$ npm install
npm install
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! path /Checkouts/test/node_modules/material-ui-pagination/node_modules/webpack/bin/webpack.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Checkouts/test/node_modules/material-ui-pagination/node_modules/webpack/bin/webpack.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/Checkouts/test/node_modules/material-ui-pagination/node_modules/webpack/bin/webpack.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Checkouts/test/npm-debug.log
```

I also get the same output when I do in an empty directory `npm install material-ui-pagination`.

**Comment by esprehn** [comment]
Are you sure that devDependencies are installed for subpackages? I thought they were for developing that package itself. Looking locally things in devDependencies inside our dependencies do not seem to recursively install.

I'm also not sure it's safe to assume that webpack will be inside the material-ui-pagination directory like this, I think if the version it expects is available as a sibling dependency it'll be installed along side material-ui-pagination instead of inside it?

**Comment by esprehn** [comment]
See also:
https://stackoverflow.com/questions/39080160/how-to-install-npm-devdependencies-recursively

Which makes me think this won't work as expected:
https://github.com/lo-tp/material-ui-pagination/blob/master/package.json#L56
https://github.com/lo-tp/material-ui-pagination/blob/master/package.json#L17

**Comment by ca0abinary** [comment]
Having the same issue. Since it's a team build I had to pin to `1.0.x` to get the build running again.

**Comment by lo-tp** [comment]
@ca0abinary 
@esprehn 
Sorry for all the inconvenience guys.
Now I've found the problem and fixed it.
Next time I'll try to be more prudent when updating the npm package.

**Comment by HawkeyePierce89** [comment]
Stop, stop, stop.

Now it does not work for me on Windows.

> "node_modules" не является внутренней или внешней
> командой, исполняемой программой или пакетным файлом.
(not an internal or external command, operable program or batch file)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! material-ui-pagination@1.1.2 build: `node_modules/webpack/bin/webpack.js --progress --colors  --config webpack.config.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the material-ui-pagination@1.1.2 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\1\AppData\Roaming\npm-cache\_logs\2017-08-11T13_12_43_079Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! material-ui-pagination@1.1.2 prepublish: `npm run build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the material-ui-pagination@1.1.2 prepublish script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

@esprehn Why are you checking on the old versions?

> lerna ERR! execute npm ERR! node v6.10.3
> lerna ERR! execute npm ERR! npm  v3.10.10

**Comment by lo-tp** [comment]
@HawkeyePierce89 
Use version 1.10 as a makeshift temporarily please.
I'm trying to figure out the problem.

**Comment by lo-tp** [comment]
@HawkeyePierce89 
I added better-run to solve the cross-platform installation problem at a [new branch](https://github.com/lo-tp/material-ui-pagination/tree/bugfix/windowsInstallation).
Please check it out and see if it works so we can merge it to the master.

**Comment by HawkeyePierce89** [comment]
@lo-tp 
looks better

> c:\git\material-ui-pagination-bugfix-windowsInstallation>npm install
> npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
> npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
> npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
> 
> > material-ui-pagination@1.1.2 prepublish c:\git\material-ui-pagination-bugfix-windowsInstallation
> > better-npm-run build
> 
> running better-npm-run in c:\git\material-ui-pagination-bugfix-windowsInstallation
> Executing script: build
> 
> to be executed: "webpack --progress --colors  --config webpack.config.js"   Hash: 41cd587e583927017f2c
> Version: webpack 1.15.0
> Time: 5224ms
>    Asset     Size  Chunks             Chunk Names
> index.js  15.7 kB       0  [emitted]  main
>    [0] multi main 28 bytes {0} [built]
>     + 14 hidden modules
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none was installed.
> npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-react@^7.1.0 but none was installed.
> npm WARN material-ui-pagination@1.1.2 No license field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> added 845 packages in 172.648s

**Comment by lo-tp** [comment]
@HawkeyePierce89 
Can I assume that everything works fine in your windows environment with the new branch?

**Comment by HawkeyePierce89** [comment]
@lo-tp 

Yes, everything seems to be installed and working correctly
