### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by jgreubel** [lo-tp/material-ui-pagination#22]
Hey again.  Your package specifies that you require a react peer dependency of "react": "^15.5.4", and "react-dom": "^15.5.4" which will complain if react v16 is used instead. 

Have you tested this component on react 16?  I've just updated my project to use react 16 and this package, and it worked as expected.  I would suggest testing it yourself and then changing that version requirement to allow both react 15 and 16.  See this documents page for tips: https://docs.npmjs.com/misc/semver

**Comment by lo-tp** [comment]
Can you make a PR about this?
