### ISSUE TITLE
Previous & Next buttons

### ISSUE THREAD

**Issue by nataze** [lo-tp/material-ui-pagination#23]
Hello, I was wondering if there's a way to add links that go to the next and previous pages. Currently, it has a button to go to the last page like this:  
..345 >|
Hitting the end button takes us all the way to the last page in the list.
But I'd like it to look like this:
..345 > >|
Where the middle button takes us to the page 346.

**Comment by lo-tp** [comment]
Customizations to previous and next buttons can be achieved by CSS.
