### ISSUE TITLE
Modifications for Material UI Next

### ISSUE THREAD

**Issue by mustafagonul** [lo-tp/material-ui-pagination#24]
I would like to create a pull request for the modifications for Material UI Next on my fork. I don't want to create a PR for the master branch, it is not appropriate. I appreciate if you could create a branch for the modifications.

**Comment by lo-tp** [comment]
Can you elaborate on the reason why PR is not appropriate at this circumstance?

**Comment by mustafagonul** [comment]
I don't know if you are familiar with Material UI Next (v1.0.0), lots of things are changed. For example buttons and etc. If we decide to push my changes to your master branch, lots of codes using Material UI (v0.20) of others will be broken. For keeping others safe and to be prepared for the future, creating an other branch, I think, will be better. 

Please check **next** branch my fork: [mustafagonul/material-ui-pagination/next](https://github.com/mustafagonul/material-ui-pagination/tree/next)

**Comment by lo-tp** [comment]
Then can I say a separate repo dedicated for Mateiral UI Next is better?

**Comment by mustafagonul** [comment]
Yes, that would be better, I don't find ethical just copying your code and committing my current changes for Material UI Next without your permission. I will proceed as you wish. You are the owner of the repo :)

**Comment by lo-tp** [comment]
Maybe we can do it in this way:
- The existing version 1.X.X  for the original material-ui.
- A new version 2.X.X for material-ui-next.

No separate repo required.

When material-ui-next matures, we can render version 1.X.X as obsolete.

I think this would be more convenient for the user.

What do you think about this plan?

**Comment by mustafagonul** [comment]
Sorry, I could not respond in time. I am OK with your plan. If you want we can do it.
