### ISSUE TITLE
React 16?

### ISSUE THREAD

**Issue by jarib** [lo-tp/material-ui-pagination#26]
Any chance of getting `peerDependencies` to support `react` and `react-dom` 16?

**Comment by lo-tp** [comment]
Yes.

Can you try installing [react-16](https://github.com/lo-tp/material-ui-pagination/tree/react-16) to see if it works?

**Comment by jarib** [comment]
Looking good! 👍

**Comment by lo-tp** [comment]
Now one can install the next version if he or she need the support of react 16 with `npm install material-ui-pagination@next`!
Cheers
