### ISSUE TITLE
Set displayName on the Pagination component for testing

### ISSUE THREAD

**Issue by jgreubel** [lo-tp/material-ui-pagination#8]
Hey, first off wanted to say I just started using this yesterday and it has been very easy to work with.  

However, I do a lot testing and right now this component doesn't play too nice with [Enzyme](http://airbnb.io/enzyme/), probably the most popular testing library for React projects. 

Specifically, Enzyme lets you render a component and then test how the child components are interacted with, like what values are passed in to their props.  But right now it is very hard to 'select' your Pagination component because it does not have a displayName.  Could you add a displayName to your component with the name ideally being "Pagination"?

See this for more information: http://airbnb.io/enzyme/docs/api/selector.html#3-a-react-component-s-displayname & https://facebook.github.io/react/docs/react-component.html#displayname

**Comment by lo-tp** [comment]
Working on this now.

**Comment by lo-tp** [comment]
Hi @jgreubel .
I've added the `displayName` property in accordance with the way you described above.
Now I want to ensure if I have done it in the right way.
So could you check if the modification I made in the [bugfix/displayName](https://github.com/lo-tp/material-ui-pagination/tree/bugfix/displayName) branch is what you want so I can merge it to the master and update the npm package?

**Comment by jgreubel** [comment]
@lo-tp I checked it out and it worked great.  I could now select it by 'Pagination'

**Comment by lo-tp** [comment]
Hi @jgreubel .
Npm package updated, modification merged.
Everything should work smoothly now.
Cheers
